language: ruby
version: 1.9.3
before_script:
- sh -e /etc/init.d/xvfb start
script: PADRINO_ENV=travis padrino rake
bundler_args: --without development
before_install: 
  - sudo apt-get update -qq 
  - sudo apt-get install -qq postgresql-server-dev-9.3
env:
  - HOME_PATH=$HOME
